In [1]:
import numpy as np 
import pandas as pd 


from sklearn.preprocessing import StandardScaler

### Load dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.drop(columns = ['id','Unnamed: 32'], inplace = True)

In [5]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

### Train test split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, :1], test_size = 0.2)

### Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

### Label Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

c:\Users\sghor\Desktop\Souvik\Programming\MMVL project requirments\Machine learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\sghor\Desktop\Souvik\Programming\MMVL project requirments\Machine learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [11]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0])

In [12]:
y_test

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0])

### Numpy array to tensor conversion

In [13]:
import torch
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

### Defining model

In [31]:
class mysimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, requires_grad=True, dtype = torch.float64)
        self.bias = torch.zeros(1, requires_grad=True, dtype = torch.float64)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss(self, y_pred, y):
        epsilon =1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        loss = -(y * torch.log(y_pred) + (1-y)* torch.log(1-y_pred)).mean()
        return loss

#### Important parameters

In [35]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [36]:
model = mysimpleNN(X_train_tensor)
for epoch in range(epochs):
    # forward
    y_pred = model.forward(X_train_tensor)


    # loss
    loss = model.loss(y_pred, y_train_tensor)
    print(loss)



    # Backward pass
    loss.backward()

    # Parameters updates
    with torch.no_grad():
        model.weights -= learning_rate *model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #print loss in each epoch
    print(f'Epoch: {epoch +1}, Loss: {loss.item()}')

tensor(4.1562, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 1, Loss: 4.156234998161104
tensor(4.0511, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 2, Loss: 4.051087480405769
tensor(3.9433, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 3, Loss: 3.943282499870638
tensor(3.8296, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 4, Loss: 3.8295951160895823
tensor(3.7076, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 5, Loss: 3.7076408409073403
tensor(3.5755, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 6, Loss: 3.575517696864882
tensor(3.4378, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 7, Loss: 3.4377684388688925
tensor(3.2984, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 8, Loss: 3.298357807850196
tensor(3.1543, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 9, Loss: 3.1542902702338553
tensor(3.0046, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 10, Loss: 3.004588603669279
tensor(2.8509, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 11, Loss: 2.850917576511826
tensor(2.6898, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 12, Loss: 2.6897974545574597
tensor(2.5297, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 13, Loss: 2.5297284756142293
tensor(2.3672, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 14, Loss: 2.3672374736189647
tensor(2.2103, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 15, Loss: 2.21030769058641
tensor(2.0549, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 16, Loss: 2.0549365863458497
tensor(1.8989, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 17, Loss: 1.8989282948105732
tensor(1.7459, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 18, Loss: 1.7458869663833738
tensor(1.5976, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 19, Loss: 1.5976092538169253
tensor(1.4588, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 20, Loss: 1.4587701595666842
tensor(1.3348, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 21, Loss: 1.3347807339753643
tensor(1.2267, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 22, Loss: 1.2266872602932832
tensor(1.1349, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 23, Loss: 1.1348943512850267
tensor(1.0589, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 24, Loss: 1.0588798564981288
tensor(0.9972, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 25, Loss: 0.9971648773060883

In [37]:
model.weights

tensor([[ 0.0883],
        [ 0.4104],
        [ 0.2053],
        [-0.0857],
        [-0.0059],
        [ 0.0697],
        [ 0.2620],
        [-0.3827],
        [ 0.4023],
        [ 0.5963],
        [-0.3315],
        [ 0.6207],
        [ 0.1615],
        [ 0.2386],
        [-0.0838],
        [ 0.0369],
        [ 0.1649],
        [ 0.0497],
        [ 0.0123],
        [ 0.1243],
        [-0.2209],
        [ 0.1197],
        [ 0.3321],
        [-0.2249],
        [-0.2137],
        [ 0.3494],
        [-0.5180],
        [-0.0552],
        [ 0.4536],
        [ 0.0538]], dtype=torch.float64, requires_grad=True)

In [38]:
model.bias

tensor([-0.0838], dtype=torch.float64, requires_grad=True)

### Evalutation

In [51]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)

    y_pred = (y_pred > 0.8).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'accuracy = {accuracy}')

accuracy = 0.6009541153907776