In [167]:
import numpy as np 
import pandas as pd 


from sklearn.preprocessing import StandardScaler

### Load dataset

In [168]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [169]:
df.drop(columns = ['id','Unnamed: 32'], inplace = True)

In [170]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

### Train test split

In [171]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, :1], test_size = 0.2)

### Scaling

In [172]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

### Label Encoding

In [173]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

c:\Users\sghor\Desktop\Souvik\Programming\MMVL project requirments\Machine learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\sghor\Desktop\Souvik\Programming\MMVL project requirments\Machine learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [174]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [175]:
y_test

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1])

### Numpy array to tensor conversion

In [176]:
import torch
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [177]:
from torch.utils.data import DataLoader, Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return len(self.features)

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [178]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [179]:

train_loader = DataLoader(train_dataset, batch_size=32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = True)

### Defining model

In [180]:
import torch.nn as nn

class mysimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

#### Important parameters

In [181]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [182]:
model = mysimpleNN(X_train_tensor.shape[1])
loss_func = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:

        y_pred = model(batch_features)
        loss = loss_func(y_pred, batch_labels.view(-1,1))

        optimizer.zero_grad()
        loss.backward()

        optimizer.step()

        print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6705090403556824
Epoch: 1, Loss: 0.5403776168823242
Epoch: 1, Loss: 0.4458412230014801
Epoch: 1, Loss: 0.39742445945739746
Epoch: 1, Loss: 0.368463933467865
Epoch: 1, Loss: 0.2573740482330322
Epoch: 1, Loss: 0.2990085780620575
Epoch: 1, Loss: 0.284290611743927
Epoch: 1, Loss: 0.26252079010009766
Epoch: 1, Loss: 0.23245741426944733
Epoch: 1, Loss: 0.2926921546459198
Epoch: 1, Loss: 0.16624775528907776
Epoch: 1, Loss: 0.22402292490005493
Epoch: 1, Loss: 0.18865562975406647
Epoch: 1, Loss: 0.19589319825172424
Epoch: 2, Loss: 0.25516024231910706
Epoch: 2, Loss: 0.20463216304779053
Epoch: 2, Loss: 0.15058080852031708
Epoch: 2, Loss: 0.26038604974746704
Epoch: 2, Loss: 0.1577850729227066
Epoch: 2, Loss: 0.17321191728115082
Epoch: 2, Loss: 0.2130410522222519
Epoch: 2, Loss: 0.16524648666381836
Epoch: 2, Loss: 0.16513800621032715
Epoch: 2, Loss: 0.1498681604862213
Epoch: 2, Loss: 0.11441519856452942
Epoch: 2, Loss: 0.10364867001771927
Epoch: 2, Loss: 0.18886679410934448
Epoch: 2, Loss: 0.14905385673046112
Epoch: 2, Loss: 0.11999042332172394
Epoch: 3, Loss: 0.18803749978542328
Epoch: 3, Loss: 0.11505964398384094
Epoch: 3, Loss: 0.10512025654315948
Epoch: 3, Loss: 0.15424996614456177
Epoch: 3, Loss: 0.3115193247795105
Epoch: 3, Loss: 0.12099918723106384
Epoch: 3, Loss: 0.1639169156551361
Epoch: 3, Loss: 0.1630220264196396
Epoch: 3, Loss: 0.09766583889722824
Epoch: 3, Loss: 0.08347183465957642
Epoch: 3, Loss: 0.0783892348408699
Epoch: 3, Loss: 0.14624440670013428
Epoch: 3, Loss: 0.07529227435588837
Epoch: 3, Loss: 0.14337129890918732
Epoch: 3, Loss: 0.19583110511302948
Epoch: 4, Loss: 0.12408376485109329
Epoch: 4, Loss: 0.15364105999469757
Epoch: 4, Loss: 0.12864765524864197
Epoch: 4, Loss: 0.09375936537981033
Epoch: 4, Loss: 0.09419625997543335
Epoch: 4, Loss: 0.10757088661193848
Epoch: 4, Loss: 0.15604960918426514
Epoch: 4, Loss: 0.16979919373989105
Epoch: 4, Loss: 0.08182486891746521
Epoch: 4, Loss: 0.09171057492494583
Epoch: 4, Loss: 0.11135038733482361
Epoch: 4, Loss: 0.1459721326828003
Epoch: 4, Loss: 0.10802145302295685
Epoch: 4, Loss: 0.1709597259759903
Epoch: 4, Loss: 0.030180955305695534
Epoch: 5, Loss: 0.12359077483415604
Epoch: 5, Loss: 0.0905870720744133
Epoch: 5, Loss: 0.12456414848566055
Epoch: 5, Loss: 0.09945829957723618
Epoch: 5, Loss: 0.2049754410982132
Epoch: 5, Loss: 0.1371343582868576
Epoch: 5, Loss: 0.10654781013727188
Epoch: 5, Loss: 0.08316224813461304
Epoch: 5, Loss: 0.1480998545885086
Epoch: 5, Loss: 0.035892244428396225
Epoch: 5, Loss: 0.08798359334468842
Epoch: 5, Loss: 0.12240039557218552
Epoch: 5, Loss: 0.11826460063457489
Epoch: 5, Loss: 0.09387575089931488
Epoch: 5, Loss: 0.06076837703585625
Epoch: 6, Loss: 0.08551118522882462
Epoch: 6, Loss: 0.06985452026128769
Epoch: 6, Loss: 0.2333589792251587
Epoch: 6, Loss: 0.12827104330062866
Epoch: 6, Loss: 0.085528664290905
Epoch: 6, Loss: 0.04883845895528793
Epoch: 6, Loss: 0.11759310960769653
Epoch: 6, Loss: 0.12937670946121216
Epoch: 6, Loss: 0.07534243911504745
Epoch: 6, Loss: 0.07290241122245789
Epoch: 6, Loss: 0.07393598556518555
Epoch: 6, Loss: 0.10636746883392334
Epoch: 6, Loss: 0.09314928203821182
Epoch: 6, Loss: 0.12366706132888794
Epoch: 6, Loss: 0.1697070300579071
Epoch: 7, Loss: 0.07024864107370377
Epoch: 7, Loss: 0.08001595735549927
Epoch: 7, Loss: 0.1634296476840973
Epoch: 7, Loss: 0.08579112589359283
Epoch: 7, Loss: 0.10118269920349121
Epoch: 7, Loss: 0.112665556371212
Epoch: 7, Loss: 0.14575782418251038
Epoch: 7, Loss: 0.07109212130308151
Epoch: 7, Loss: 0.08165471255779266
Epoch: 7, Loss: 0.09138674288988113
Epoch: 7, Loss: 0.04550608620047569
Epoch: 7, Loss: 0.10064052045345306
Epoch: 7, Loss: 0.06719974428415298
Epoch: 7, Loss: 0.15228599309921265
Epoch: 7, Loss: 0.11533688008785248
Epoch: 8, Loss: 0.06921571493148804
Epoch: 8, Loss: 0.1266951560974121
Epoch: 8, Loss: 0.09834152460098267
Epoch: 8, Loss: 0.11455211043357849
Epoch: 8, Loss: 0.0626750960946083
Epoch: 8, Loss: 0.10274691134691238
Epoch: 8, Loss: 0.05403957888484001
Epoch: 8, Loss: 0.08624088764190674
Epoch: 8, Loss: 0.08217214047908783
Epoch: 8, Loss: 0.1348000168800354
Epoch: 8, Loss: 0.1464097797870636
Epoch: 8, Loss: 0.11748550832271576
Epoch: 8, Loss: 0.02891375869512558
Epoch: 8, Loss: 0.09849388897418976
Epoch: 8, Loss: 0.042279310524463654
Epoch: 9, Loss: 0.09483703970909119
Epoch: 9, Loss: 0.07665417343378067
Epoch: 9, Loss: 0.0624873973429203
Epoch: 9, Loss: 0.06638332456350327
Epoch: 9, Loss: 0.18121255934238434
Epoch: 9, Loss: 0.06610021740198135
Epoch: 9, Loss: 0.138212651014328
Epoch: 9, Loss: 0.10189544409513474
Epoch: 9, Loss: 0.06981939822435379
Epoch: 9, Loss: 0.11637699604034424
Epoch: 9, Loss: 0.0700051337480545
Epoch: 9, Loss: 0.05123838782310486
Epoch: 9, Loss: 0.08936897665262222
Epoch: 9, Loss: 0.07128973305225372
Epoch: 9, Loss: 0.10325761139392853
Epoch: 10, Loss: 0.050617415457963943
Epoch: 10, Loss: 0.14116041362285614
Epoch: 10, Loss: 0.03193345665931702
Epoch: 10, Loss: 0.07041420787572861
Epoch: 10, Loss: 0.09122278541326523
Epoch: 10, Loss: 0.0880819782614708
Epoch: 10, Loss: 0.04292578622698784
Epoch: 10, Loss: 0.07885662466287613
Epoch: 10, Loss: 0.1392175406217575
Epoch: 10, Loss: 0.09559153765439987
Epoch: 10, Loss: 0.11570948362350464
Epoch: 10, Loss: 0.07972459495067596
Epoch: 10, Loss: 0.10364855825901031
Epoch: 10, Loss: 0.08683992177248001
Epoch: 10, Loss: 0.06806667894124985
Epoch: 11, Loss: 0.1024247258901596
Epoch: 11, Loss: 0.1131594181060791
Epoch: 11, Loss: 0.06647881865501404
Epoch: 11, Loss: 0.09028405696153641
Epoch: 11, Loss: 0.036749307066202164
Epoch: 11, Loss: 0.17393308877944946
Epoch: 11, Loss: 0.09450029581785202
Epoch: 11, Loss: 0.0811539888381958
Epoch: 11, Loss: 0.04861283674836159
Epoch: 11, Loss: 0.12578251957893372
Epoch: 11, Loss: 0.07375670224428177
Epoch: 11, Loss: 0.039615780115127563
Epoch: 11, Loss: 0.05858399346470833
Epoch: 11, Loss: 0.07820719480514526
Epoch: 11, Loss: 0.05878268927335739
Epoch: 12, Loss: 0.05704746022820473
Epoch: 12, Loss: 0.053411807864904404
Epoch: 12, Loss: 0.06338769197463989
Epoch: 12, Loss: 0.07146581262350082
Epoch: 12, Loss: 0.04138081520795822
Epoch: 12, Loss: 0.13337469100952148
Epoch: 12, Loss: 0.036269623786211014
Epoch: 12, Loss: 0.019040768966078758
Epoch: 12, Loss: 0.09521086513996124
Epoch: 12, Loss: 0.11406344920396805
Epoch: 12, Loss: 0.0968100056052208
Epoch: 12, Loss: 0.044948138296604156
Epoch: 12, Loss: 0.122016541659832
Epoch: 12, Loss: 0.17655536532402039
Epoch: 12, Loss: 0.16798286139965057
Epoch: 13, Loss: 0.04487733170390129
Epoch: 13, Loss: 0.024232173338532448
Epoch: 13, Loss: 0.08604405075311661
Epoch: 13, Loss: 0.04673437029123306
Epoch: 13, Loss: 0.07622763514518738
Epoch: 13, Loss: 0.03790256753563881
Epoch: 13, Loss: 0.10263218730688095
Epoch: 13, Loss: 0.09979266673326492
Epoch: 13, Loss: 0.09069059044122696
Epoch: 13, Loss: 0.13941553235054016
Epoch: 13, Loss: 0.017567675560712814
Epoch: 13, Loss: 0.17845845222473145
Epoch: 13, Loss: 0.09508255869150162
Epoch: 13, Loss: 0.08799014240503311
Epoch: 13, Loss: 0.010105269029736519
Epoch: 14, Loss: 0.0892774686217308
Epoch: 14, Loss: 0.1209920197725296
Epoch: 14, Loss: 0.09631074219942093
Epoch: 14, Loss: 0.05281025171279907
Epoch: 14, Loss: 0.13150401413440704
Epoch: 14, Loss: 0.1017361581325531
Epoch: 14, Loss: 0.04811472073197365
Epoch: 14, Loss: 0.0410192608833313
Epoch: 14, Loss: 0.08077725768089294
Epoch: 14, Loss: 0.05791376158595085
Epoch: 14, Loss: 0.08189092576503754
Epoch: 14, Loss: 0.07214491069316864
Epoch: 14, Loss: 0.0632706731557846
Epoch: 14, Loss: 0.06279081851243973
Epoch: 14, Loss: 0.02540416829288006
Epoch: 15, Loss: 0.06077789142727852
Epoch: 15, Loss: 0.055788129568099976
Epoch: 15, Loss: 0.04852232709527016
Epoch: 15, Loss: 0.07547485083341599
Epoch: 15, Loss: 0.07347556948661804
Epoch: 15, Loss: 0.055556733161211014
Epoch: 15, Loss: 0.047033753246068954
Epoch: 15, Loss: 0.07684274017810822
Epoch: 15, Loss: 0.15992723405361176
Epoch: 15, Loss: 0.13274602591991425
Epoch: 15, Loss: 0.12208306789398193
Epoch: 15, Loss: 0.03941507637500763
Epoch: 15, Loss: 0.04898466914892197
Epoch: 15, Loss: 0.07685001939535141
Epoch: 15, Loss: 0.0561186783015728
Epoch: 16, Loss: 0.07660701125860214
Epoch: 16, Loss: 0.09302455186843872
Epoch: 16, Loss: 0.11825541406869888
Epoch: 16, Loss: 0.09515369683504105
Epoch: 16, Loss: 0.06499802321195602
Epoch: 16, Loss: 0.04269176721572876
Epoch: 16, Loss: 0.045718301087617874
Epoch: 16, Loss: 0.07854141294956207
Epoch: 16, Loss: 0.055302925407886505
Epoch: 16, Loss: 0.04291170462965965
Epoch: 16, Loss: 0.07989751547574997
Epoch: 16, Loss: 0.11119569092988968
Epoch: 16, Loss: 0.08932820707559586
Epoch: 16, Loss: 0.06611435115337372
Epoch: 16, Loss: 0.019348839297890663
Epoch: 17, Loss: 0.06728454679250717
Epoch: 17, Loss: 0.0498526431620121
Epoch: 17, Loss: 0.05644187331199646
Epoch: 17, Loss: 0.07018887251615524
Epoch: 17, Loss: 0.06334295868873596
Epoch: 17, Loss: 0.04126255214214325
Epoch: 17, Loss: 0.07634229212999344
Epoch: 17, Loss: 0.05725626274943352
Epoch: 17, Loss: 0.15927723050117493
Epoch: 17, Loss: 0.04295122250914574
Epoch: 17, Loss: 0.11309443414211273
Epoch: 17, Loss: 0.1230325996875763
Epoch: 17, Loss: 0.026142284274101257
Epoch: 17, Loss: 0.0662628710269928
Epoch: 17, Loss: 0.15649090707302094
Epoch: 18, Loss: 0.10470589250326157
Epoch: 18, Loss: 0.08688664436340332
Epoch: 18, Loss: 0.07911993563175201
Epoch: 18, Loss: 0.1282481849193573
Epoch: 18, Loss: 0.02454557828605175
Epoch: 18, Loss: 0.13320617377758026
Epoch: 18, Loss: 0.09378688037395477
Epoch: 18, Loss: 0.05748683586716652
Epoch: 18, Loss: 0.041469138115644455
Epoch: 18, Loss: 0.07713025063276291
Epoch: 18, Loss: 0.06864140927791595
Epoch: 18, Loss: 0.022021574899554253
Epoch: 18, Loss: 0.06856927275657654
Epoch: 18, Loss: 0.038337673991918564
Epoch: 18, Loss: 0.02333531156182289
Epoch: 19, Loss: 0.08865336328744888
Epoch: 19, Loss: 0.035235755145549774
Epoch: 19, Loss: 0.04229170083999634
Epoch: 19, Loss: 0.07483138889074326
Epoch: 19, Loss: 0.13983237743377686
Epoch: 19, Loss: 0.06026354432106018
Epoch: 19, Loss: 0.10346320271492004
Epoch: 19, Loss: 0.04170931503176689
Epoch: 19, Loss: 0.0545768216252327
Epoch: 19, Loss: 0.19481053948402405
Epoch: 19, Loss: 0.05348268151283264
Epoch: 19, Loss: 0.052503470331430435
Epoch: 19, Loss: 0.04483814910054207
Epoch: 19, Loss: 0.023089934140443802
Epoch: 19, Loss: 0.01467342022806406
Epoch: 20, Loss: 0.04034050926566124
Epoch: 20, Loss: 0.057767610996961594
Epoch: 20, Loss: 0.0941421240568161
Epoch: 20, Loss: 0.06363638490438461
Epoch: 20, Loss: 0.08502273261547089
Epoch: 20, Loss: 0.06515762209892273
Epoch: 20, Loss: 0.1853075921535492
Epoch: 20, Loss: 0.10252009332180023
Epoch: 20, Loss: 0.0315498411655426
Epoch: 20, Loss: 0.12152039259672165
Epoch: 20, Loss: 0.03785308822989464
Epoch: 20, Loss: 0.020720988512039185
Epoch: 20, Loss: 0.024938682094216347
Epoch: 20, Loss: 0.06652352213859558
Epoch: 20, Loss: 0.008195523172616959
Epoch: 21, Loss: 0.07164500653743744
Epoch: 21, Loss: 0.06840375065803528
Epoch: 21, Loss: 0.07652246206998825
Epoch: 21, Loss: 0.03851185739040375
Epoch: 21, Loss: 0.08381913602352142
Epoch: 21, Loss: 0.012353086844086647
Epoch: 21, Loss: 0.04450731724500656
Epoch: 21, Loss: 0.075499027967453
Epoch: 21, Loss: 0.10674450546503067
Epoch: 21, Loss: 0.03567691519856453
Epoch: 21, Loss: 0.1166384145617485
Epoch: 21, Loss: 0.08952608704566956
Epoch: 21, Loss: 0.04893343150615692
Epoch: 21, Loss: 0.05718487873673439
Epoch: 21, Loss: 0.2813510596752167
Epoch: 22, Loss: 0.1648050844669342
Epoch: 22, Loss: 0.040630631148815155
Epoch: 22, Loss: 0.06260742247104645
Epoch: 22, Loss: 0.04791610315442085
Epoch: 22, Loss: 0.08801966160535812
Epoch: 22, Loss: 0.061584439128637314
Epoch: 22, Loss: 0.1459483504295349
Epoch: 22, Loss: 0.05309437960386276
Epoch: 22, Loss: 0.026893455535173416
Epoch: 22, Loss: 0.1335267871618271
Epoch: 22, Loss: 0.058624085038900375
Epoch: 22, Loss: 0.02062945067882538
Epoch: 22, Loss: 0.0459311418235302
Epoch: 22, Loss: 0.02022416889667511
Epoch: 22, Loss: 0.021625550463795662
Epoch: 23, Loss: 0.05688711255788803
Epoch: 23, Loss: 0.05694155767560005
Epoch: 23, Loss: 0.04612927511334419
Epoch: 23, Loss: 0.030198832973837852
Epoch: 23, Loss: 0.08910210430622101
Epoch: 23, Loss: 0.09212590008974075
Epoch: 23, Loss: 0.05930212885141373
Epoch: 23, Loss: 0.08548160642385483
Epoch: 23, Loss: 0.08304933458566666
Epoch: 23, Loss: 0.06376864016056061
Epoch: 23, Loss: 0.031826287508010864
Epoch: 23, Loss: 0.12186227738857269
Epoch: 23, Loss: 0.05889638885855675
Epoch: 23, Loss: 0.06808371841907501
Epoch: 23, Loss: 0.08492457121610641
Epoch: 24, Loss: 0.08867312222719193
Epoch: 24, Loss: 0.030651982873678207
Epoch: 24, Loss: 0.10165899246931076
Epoch: 24, Loss: 0.1110161542892456
Epoch: 24, Loss: 0.015254803001880646
Epoch: 24, Loss: 0.05232086405158043
Epoch: 24, Loss: 0.062456414103507996
Epoch: 24, Loss: 0.05061846226453781
Epoch: 24, Loss: 0.090875543653965
Epoch: 24, Loss: 0.05128306522965431
Epoch: 24, Loss: 0.021854465827345848
Epoch: 24, Loss: 0.09164231270551682
Epoch: 24, Loss: 0.11151985824108124
Epoch: 24, Loss: 0.06844407320022583
Epoch: 24, Loss: 0.007770860102027655
Epoch: 25, Loss: 0.06724102050065994
Epoch: 25, Loss: 0.07372647523880005
Epoch: 25, Loss: 0.0320943221449852
Epoch: 25, Loss: 0.09303049743175507
Epoch: 25, Loss: 0.08437826484441757
Epoch: 25, Loss: 0.04963881894946098
Epoch: 25, Loss: 0.05768115073442459
Epoch: 25, Loss: 0.015217287465929985
Epoch: 25, Loss: 0.06364293396472931
Epoch: 25, Loss: 0.08279682695865631
Epoch: 25, Loss: 0.04112793505191803
Epoch: 25, Loss: 0.06319737434387207
Epoch: 25, Loss: 0.10892531275749207
Epoch: 25, Loss: 0.024766506627202034
Epoch: 25, Loss: 0.3789677619934082

In [183]:
model.linear.weight

Parameter containing:
tensor([[ 0.6474,  0.7375,  0.5846,  0.3908,  0.1782,  0.0410,  0.6277,  0.3911,
          0.1168, -0.2647,  0.6415, -0.0161,  0.3406,  0.3195,  0.0425, -0.3425,
         -0.1501,  0.0978, -0.2634, -0.3248,  0.8212,  0.5864,  0.5553,  0.6910,
          0.6214,  0.2002,  0.6211,  0.5611,  0.4483,  0.1248]],
       requires_grad=True)

In [184]:
model.linear.bias

Parameter containing:
tensor([-0.4878], requires_grad=True)

### Evalutation

In [185]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)

    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean().item()
    print(f'accuracy = {accuracy}')

accuracy = 0.5260080099105835