In [74]:
import numpy as np 
import pandas as pd 


from sklearn.preprocessing import StandardScaler

### Load dataset

In [75]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [76]:
df.drop(columns = ['id','Unnamed: 32'], inplace = True)

In [77]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

### Train test split

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, :1], test_size = 0.2)

### Scaling

In [79]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

### Label Encoding

In [80]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

c:\Users\sghor\Desktop\Souvik\Programming\MMVL project requirments\Machine learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\sghor\Desktop\Souvik\Programming\MMVL project requirments\Machine learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [81]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0])

In [82]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1])

### Numpy array to tensor conversion

In [83]:
import torch
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

### Defining model

In [90]:
import torch.nn as nn

class mysimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

#### Important parameters

In [85]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [91]:
model = mysimpleNN(X_train_tensor.shape[1])
loss_func = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):

    y_pred = model(X_train_tensor)
    loss = loss_func(y_pred, y_train_tensor.view(-1,1))

    optimizer.zero_grad()
    loss.backward()

    optimizer.step()

    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8724693655967712
Epoch: 2, Loss: 0.6140868663787842
Epoch: 3, Loss: 0.4843485653400421
Epoch: 4, Loss: 0.41147780418395996
Epoch: 5, Loss: 0.3644823729991913
Epoch: 6, Loss: 0.33124640583992004
Epoch: 7, Loss: 0.30624234676361084
Epoch: 8, Loss: 0.28658822178840637
Epoch: 9, Loss: 0.2706279456615448
Epoch: 10, Loss: 0.25733843445777893
Epoch: 11, Loss: 0.24605120718479156
Epoch: 12, Loss: 0.23630982637405396
Epoch: 13, Loss: 0.22779084742069244
Epoch: 14, Loss: 0.22025823593139648
Epoch: 15, Loss: 0.21353524923324585
Epoch: 16, Loss: 0.2074866145849228
Epoch: 17, Loss: 0.2020067721605301
Epoch: 18, Loss: 0.1970120668411255
Epoch: 19, Loss: 0.192435160279274
Epoch: 20, Loss: 0.18822117149829865
Epoch: 21, Loss: 0.18432480096817017
Epoch: 22, Loss: 0.18070834875106812
Epoch: 23, Loss: 0.1773400902748108
Epoch: 24, Loss: 0.17419317364692688
Epoch: 25, Loss: 0.17124459147453308

In [97]:
model.linear.weight

Parameter containing:
tensor([[ 0.2591,  0.1224,  0.1254,  0.1619,  0.1530,  0.2354,  0.0645,  0.2094,
         -0.0177, -0.1981,  0.2133,  0.0495,  0.2192,  0.2612, -0.0681,  0.0611,
         -0.1627,  0.0882,  0.0719,  0.0220,  0.2588,  0.1101,  0.3916,  0.3020,
          0.1351,  0.0464,  0.3475,  0.2354,  0.0752,  0.1835]],
       requires_grad=True)

In [98]:
model.linear.bias

Parameter containing:
tensor([-0.2887], requires_grad=True)

### Evalutation

In [99]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)

    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'accuracy = {accuracy}')

accuracy = 0.5138503909111023